#!/bin/bash

ap=" --restrict-filenames --write-info-json --write-description "

cd "${HOME}/Movies"
echo "Sitting in `pwd` downloading ${1}"

#ytdlp=$(which yt-dlp)
ytdlp="/home/goz/.local/bin/yt-dlp"

echo "${ytdlp}"
#sudo ${ytdlp} -U
${ytdlp} --update-to nightly
#filename=$(${ytdlp} --cookies ${HOME}/cookies.SocialMedia.txt --user-agent facebookexternalhit/1.1 --windows-filenames --get-filename "${1}")

if [[ "${1}" =~ "tiktok.com" ]]; then
    filename=$(${ytdlp} --extractor-args "tiktok:api_hostname=api22-normal-c-useast2a.tiktokv.com" --user-agent facebookexternalhit/1.1 --windows-filenames --get-filename "${1}")
else
    filename=$(${ytdlp} --user-agent facebookexternalhit/1.1 --windows-filenames --get-filename "${1}")
fi

#filename="@StarTrekGuy  [7304431911953255722].mp4"

fullname=$(echo -n "${filename%.*}" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | sed -e 's/^-//' | sed -e 's/-$//')
videoid="${fullname##*-}"
name="${fullname%-*}"
ext="${filename##*.}"
file="${name:0:40}-${videoid}.mp4"

echo "${name} - ${videoid} - ${ext} - ${file}"

#${ytdlp} --cookies ${HOME}/cookies.SocialMedia.txt --user-agent facebookexternalhit/1.1 --windows-filenames -o "${file}" "${1}"

#--extractor-args "tiktok:api_hostname=api22-normal-c-useast2a.tiktokv.com" \
if [[ "${1}" =~ "tiktok.com" ]]; then
    ${ytdlp} -S res,ext:mp4:m4a --recode mp4 --user-agent facebookexternalhit/1.1 \
        --windows-filenames -o "${file}" \
        ${ap} \
        "${1}"
else
    ${ytdlp} -S res,ext:mp4:m4a --recode mp4 --user-agent facebookexternalhit/1.1 --windows-filenames -o "${file}" "${1}"
fi
uploaded=$(jq -r .uploader "${file%.*}.info.json")
description=$(jq -r .description "${file%.*}.info.json")
url=$(jq -r '.formats[1].http_headers.Referer' "${file%.*}.info.json")

caption="${description:0:100}
 
 @${uploaded}
 ${url}
 ${filename}"

telegram-send --video "${file}" --caption "${caption}"
videoupload -t "${filename:0:50}" -c "${caption}" "${file}"
