#!/bin/bash

# Set to 1
# Threads: _wpas_skip_publicize_25478617 
# Facebook: _wpas_skip_publicize_21764758
# Instagram: _wpas_skip_publicize_25478615
# Bluesky: _wpas_skip_publicize_25478607


declare -A category
declare -A post_format
declare -A author

tmppic="/tmp/sharepic.png"
wp_pic="/tmp/wp_pic.jpg"
font="${HOME}/Documents/Verdana.ttf"
font="${HOME}/Documents/ShantellSans-SemiBold.ttf"
captiongraphic="/tmp/caption.png"
out="/tmp/captionout.png"
outmovie="/tmp/out.mp4"
wd="/tmp"

#debug=1

post_status="publish"
[ ! -z ${debug} ] && post_status="draft"

comment() {
    [ ! -z ${debug} ] && echo "${1}"
}


# Picture category for site
category["r"]="361"
category["e"]="2074"

# Post_format for picture
post_format["r"]="359"
post_format["e"]=""

# Author
author["r"]="1"
author["e"]="1"

while getopts c:s:p:l: flag
do
    case "${flag}" in
        c) caption=${OPTARG};;
        s) site=${OPTARG};;
        p) pic=${OPTARG};;
        l) loc=${OPTARG};;
    esac
done

if [ -z ${site} ] || [ -z "${pic}" ]; then
    echo "Usage: ,sharepic -s [r|e] -c 'Caption to add' -p '/path/to/pic'"
    exit
fi

comment "Setting up the filename and extension"
ext="${pic##*.}"
md5=$(md5sum "${pic}" | awk '{print $1}' | head -c 5)
if [ -z "${caption}" ]; then
    filename=$(date +"%Y-%m-%d-%H-%M")"-${md5}.${ext}"
else
    filename=$(echo "${caption}" | tr '[:upper:]' '[:lower:]' | sed -e 's/ /-/g' -e 's/[^a-z0-9-]//g' -e 's/--*/-/g' -e 's/^-//' -e 's/-$//' | head -c 16)"-${md5}.${ext}"
fi

comment "Filename is ${filename}"

comment "Resize the ${pic} to be 1080 width (${tmppic})"
convert "${pic}" -resize 1080x "${wp_pic}"
convert "${pic}" -background black -gravity center \
  -resize 1080x1920 -extent 1080x1920 -strip "${tmppic}"

tmpwidth=$(identify -format "%w" "${tmppic}")
tmpheight=$(identify -format "%h" "${tmppic}")

comment "Set caption width and height"
cw=680
ch=250
cwminus1=$((${cw}-1))
chminus1=$((${ch}-1))
cwminus10=$((${cw}-10))
chminus10=$((${ch}-10))

comment "Working on ${tmppic} (${tmpwidth}x${tmpheight})"

comment "If there is a caption, add it to the image"
if [ ! -z "${caption}" ]; then
#    caption=$(echo "${caption}" | fmt -w 30)
#    comment "Wrap caption:
#${caption}"

#    comment "Get pointsize for text"
#    pointsize=$(convert -gravity center \
#        -background black \
#        -fill white \
#        -size ${cw}x${ch} \
#        -font "${font}" caption:"$caption" -format "%[caption:pointsize]" info:)
    notags="${caption//#[^ ]*/}"
    notags=$(echo "$notags" | xargs)

    comment "Create a white box with rounded corners"
    convert -size ${cw}x${ch} xc:none \
        -fill white \
        -draw "roundrectangle 0,0,${cwminus1},${chminus1},20,20" \
        /tmp/captionbox.png

    comment "Create caption graphic with ${font}"
    convert -background none \
        -gravity Center \
        -fill black \
        -size ${cwminus10}x${chminus10} \
        -font "${font}" \
        caption:"${notags}" \
        /tmp/captiontext.png

    comment "Composite both graphics, creating ${captiongraphic}"
    composite -gravity center \
        /tmp/captiontext.png \
        /tmp/captionbox.png \
        "${captiongraphic}"

    comment "Add caption to original graphic, creating ${out}"
    composite -geometry +200+135 \
        "${captiongraphic}" \
        "${tmppic}" \
        "${out}"
fi

if [ -z ${debug} ]; then 
    telegram-send --caption="${caption}" -i "${out}"
fi

comment "Create movie for TikTok"
rm "${outmovie}"
#/usr/bin/ffmpeg -hide_banner -loglevel error -framerate 30 -i "${out}" -t 8 -c:v libx264 -pix_fmt yuv420p -vf "scale=1080:-1,loop=-1:1,pad=ceil(iw/2)*2:ceil(ih/2)*2" -movflags faststart "${outmovie}"

/usr/bin/ffmpeg -hide_banner -loglevel error -framerate 30 -i "${out}" -t 8 -c:v libx264 -pix_fmt yuv420p -vf "scale=8000:-1,zoompan=z='zoom+0.001':x=iw/2-(iw/zoom/2):y=ih/2-(ih/zoom/2):d=8*30:s=1080x1920:fps=30,pad=ceil(iw/2)*2:ceil(ih/2)*2" -movflags faststart "${outmovie}"


if [ -z ${debug} ]; then 
    telegram-send --video "${outmovie}" --caption "${caption}"
fi

comment "Let's make it a little smaller for WP"
convert "${wp_pic}" -resize 540x540 "/tmp/${filename}"

comment "Upload image to WP..."
host=$(grep -A 1 @${site} ${HOME}/.wp-cli/config.yml | grep ssh | cut -d " " -f 6)
scp "/tmp/${filename}" "${host}:/tmp/${filename}"
imgid=$(wp @${site} media import "/tmp/${filename}" \
    --porcelain \
    --title="${caption}"
)
imgurl=$(wp @${site} db query "SELECT guid FROM wp_posts  WHERE ID=\"${imgid}\"" | head -n 2 | tail -1)
comment "Image uploaded with ID of ${imgid} (${imgurl})"

post="<!-- wp:post-featured-image /-->

<!-- wp:paragraph -->
<p>${notags}</p>

"

#comment "Create post..."
#postid=$(echo "${post}" | wp @${site} post create - \
#    --porcelain \
#    --post_type="jetpack-social-note" \
#    --post_status="draft" \
#    --post_category=${category["${site}"]})

comment "Create post..."
tags=$(echo "$caption" | grep -oE '#[A-Za-z0-9_]+' | sed 's/#//g' | paste -sd, -)
postid=$(echo "${post}" | wp @${site} post create - \
    --porcelain --post_category=${category["${site}"]} \
    --post_title="${notags}" \
    --post_author="${author["${site}"]}" \
    --post_status="draft" \
    --post_excerpt="${notags}" \
    --tags_input="${tags}")

postformat=${post_format["${site}"]}
if [ ! -z "${postformat}" ]; then
    comment "Set post_format to Image"
    wp @${site} db query "insert into wp_term_relationships (object_id,term_taxonomy_id) VALUES (\"${postid}\",\"${postformat}\")"
fi

comment "Set featured image"
wp @${site} post meta update ${postid} _thumbnail_id ${imgid}

comment "Set picture's (${imgid}) post_parent to new post (${postid})"
#wp @${site} db query "update wp_posts set post_parent=\"${postid}\" where ID=\"${imgid}\""
wp @${site} post update ${imgid} --post_parent=${postid}

comment "Turn off sharing to FB and Threads because Instagram will do that..."
#FB
wp @${site} post meta set ${postid} _wpas_skip_publicize_21764758 1
#Threads
wp @${site} post meta set ${postid} _wpas_skip_publicize_25478617 1

comment "Set link message"
wp @${site} post meta set ${postid} _wpas_mess " "

comment "Publish!"
wp @${site} post update ${postid} --post_status=${post_status}

