#!/bin/bash

declare -A category
declare -A post_format
declare -A author

tmppic="/tmp/sharepic.png"
font="${HOME}/Documents/Verdana.ttf"
font="${HOME}/Documents/ShantellSans-SemiBold.ttf"
captiongraphic="/tmp/caption.png"
out="/tmp/captionout.png"
outmovie="tmp/out.mp4"
wd="/tmp"

debug=0

post_status="publish"
[ ${debug} ] && post_status="draft"

comment() {
    [ ${debug} ] && echo "${1}"
}


# Picture category for site
category["r"]="361"
category["e"]="2074"

# Post_format for picture
post_format["r"]="359"
post_format["e"]=""

# Author
author["r"]="1"
author["e"]="1"

while getopts c:s:p:l: flag
do
    case "${flag}" in
        c) caption=${OPTARG};;
        s) site=${OPTARG};;
        p) pic=${OPTARG};;
        l) loc=${OPTARG};;
    esac
done

if [ -z ${site} ] || [ -z "${pic}" ]; then
    echo "Usage: ,sharepic -s [r|e] -c 'Caption to add' -p '/path/to/pic'"
    exit
fi

comment "Setting up the filename and extension"
ext="${pic##*.}"
md5=$(md5sum "${pic}" | awk '{print $1}' | head -c 5)
if [ -z "${caption}" ]; then
    filename=$(date +"%Y-%m-%d-%H-%M")"-${md5}.${ext}"
else
    filename=$(echo "${caption}" | tr '[:upper:]' '[:lower:]' | sed -e 's/ /-/g' -e 's/[^a-z0-9-]//g' -e 's/--*/-/g' -e 's/^-//' -e 's/-$//' | head -c 16)"-${md5}.${ext}"
fi

comment "Filename is ${filename}"

comment "Resize the ${pic} to be 1080 width (${tmppic})"
convert "${pic}" -resize 1080x1920 "${tmppic}"
tmpwidth=$(identify -format "%w" "${tmppic}")
tmpheight=$(identify -format "%h" "${tmppic}")

comment "Set caption width and height"
cw=680
ch=250
cwminus1=$((${cw}-1))
chminus1=$((${ch}-1))
cwminus10=$((${cw}-10))
chminus10=$((${ch}-10))

comment "Working on ${tmppic} (${tmpwidth}x${tmpheight})"

comment "If there is a caption, add it to the image"
if [ ! -z "${caption}" ]; then
#    caption=$(echo "${caption}" | fmt -w 30)
#    comment "Wrap caption:
#${caption}"

#    comment "Get pointsize for text"
#    pointsize=$(convert -gravity center \
#        -background black \
#        -fill white \
#        -size ${cw}x${ch} \
#        -font "${font}" caption:"$caption" -format "%[caption:pointsize]" info:)

    comment "Create a white box with rounded corners"
    convert -size ${cw}x${ch} xc:none \
        -fill white \
        -draw "roundrectangle 0,0,${cwminus1},${chminus1},20,20" \
        /tmp/captionbox.png

    comment "Create caption graphic with ${font}"
    convert -background none \
        -gravity Center \
        -fill black \
        -size ${cwminus10}x${chminus10} \
        -font "${font}" \
        caption:"${caption}" \
        /tmp/captiontext.png

    comment "Composite both graphics, creating ${captiongraphic}"
    composite -gravity center \
        /tmp/captiontext.png \
        /tmp/captionbox.png \
        "${captiongraphic}"

    comment "Add caption to original graphic, creating ${out}"
    composite -geometry +200+135 \
        "${captiongraphic}" \
        "${tmppic}" \
        "${out}"
fi

comment "Create movie for TikTok"
/usr/bin/ffmpeg -framerate 30 -i "${out}" -t 8 -c:v libx264 -pix_fmt yuv420p -vf "scale=1080:-1,loop=-1:1" -movflags faststart "${outmovie}"

if [ ! ${debug} ]; then 
    telegram-send --caption="${caption}" -i "${out}"
    telegram-send --video "${outmovie}" --caption "${caption}"
fi

comment "Upload image to WP..."
host=$(grep -A 1 @${site} ${HOME}/.wp-cli/config.yml | grep ssh | cut -d " " -f 6)
scp "${tmppic}" "${host}:/tmp/${filename}"
imgid=$(wp @${site} media import "/tmp/${filename}" \
    --porcelain \
    --title="${caption}"
)
imgurl=$(wp @${site} db query "SELECT guid FROM wp_posts  WHERE ID=\"${imgid}\"" | head -n 2 | tail -1)
comment "Image uploaded with ID of ${imgid} (${imgurl})"

post="
<img src=\"${imgurl}\">
"

comment "Create post..."
postid=$(echo "${post}" | wp @${site} post create - \
    --porcelain --post_category=${category["${site}"]} \
    --post_title="${caption}" \
    --post_author="${author["${site}"]}" \
    --post_status="${post_status}" \
    --post_excerpt="${caption}" \
    --tags_input="${tags}")

postformat=${post_format["${site}"]}
if [ ! -z "${postformat}" ]; then
    comment "Set post_format to Image"
    wp @${site} db query "insert into wp_term_relationships (object_id,term_taxonomy_id) VALUES (\"${postid}\",\"${postformat}\")"
fi

comment "Set featured image"
wp @${site} post meta update ${postid} _thumbnail_id ${imgid}

comment "Set picture's (${imgid}) post_parent to new post (${postid})"
wp @${site} db query "update wp_posts set post_parent=\"${postid}\" where ID=\"${imgid}\""
