#!/bin/bash

ostype=$(uname -a)
cdir="${HOME}/.config"

if [[ "$ostype" =~ "Darwin" ]]; then
    repos=("${cdir}/espanso" "${cdir}/iterm2prefs" "${cdir}/alfredprefs" "${cdir}/dotfiles" "${HOME}/.ssh" "${HOME}/.vim")
else
    repos=("${cdir}/dotfiles" "${HOME}/.ssh" "${HOME}/.vim" "${cdir}/kitty")
fi

cd "${HOME}/.config"

for i in ${!repos[@]};
do
    repo="${repos[$i]}"
    if [ -d "${repo}" ] && [ ! -f "${repo}/nosync" ]; then
        echo -en "Working on ${repo}... "
        cd "${repo}"
        git add --all
        git commit -am "Git Sync `date` on `hostname` $gstatus" --quiet
        git pull --quiet
        git push --quiet
        if [[ "${repo}" =~ vim ]]; then
            for i in ~/.vim/bundle/*; do git -C $i pull --quiet ; done
        fi
        echo "Done with ${repo}!"
    fi
done

