#!/bin/bash

ostype=$(uname -a)
cdir="${HOME}/.config"

if [[ "$ostype" =~ "Darwin" ]]; then
    repos=("${cdir}/espanso" "${cdir}/iterm2prefs" "${cdir}/alfredprefs" "${cdir}/dotfiles" "${cdir}/.ssh" "${cdir}/.vim")
else
    repos=("${cdir}/dotfiles" "${cdir}/.ssh" "${cdir}/.vim")
fi

cd "${HOME}/.config"

for i in ${!repos[@]};
do
    repo=${repos[$i]}
    if [ -d "${repo}" ] && [ ! -f "${repo}/nosync" ]; then
        echo "Working on ${repo}..."
        cd "${repo}"
        git add --all
        git commit -am "Git Sync `date` on `hostname` $gstatus"
        git pull
        git push
        echo "Done with ${repo}!\n"
    fi
done

