#!/bin/bash

repos=("espanso" "iterm2prefs" "alfredprefs" "dotfiles")

cd ~/.config

for i in ${!repos[@]};
do
    repo=${repos[$i]}
    echo "Working on ${repo}..."
    cd "${repo}"
    git add --all
    git commit -am "Git Sync `date` on `hostname` $gstatus"
    git pull
    git push
    cd ..
done
