#!/bin/bash

url=${1}
surl=$(~/.virtualenvs/yourls/bin/yourls shorten -s ${url} | cut -d " " -f2)
dow=$(date +"%u")

if [ "${dow}" -eq 6 ] || [ "${dow}" -eq 7 ];
then
    post="$(date -d "next monday + 1 week" +'%Y-%m-%d')-edlinks.md"
    dayofpost=$(date -d "next monday + 1 week" +'%Y-%m-%d')
    pd=$(date -d "next monday +1 week" +"%B %e, %Y")
else
    post="$(date -d "next monday" +'%Y-%m-%d')-edlinks.md"
    dayofpost=$(date -d "next monday" +'%Y-%m-%d')
    pd=$(date -d "next monday" +"%B %e, %Y")
fi

#url="https://www.imdb.com/title/tt0183790/?ref_=fn_al_tt_1"

title=$(wget -qO- "${url}" | perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si')

[ -z "${title}" ] && title="A new post added `date +'%Y-%m-%d-%H-%M'`"

slug=$(echo -n "${title}" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)
echo "Adding ${title}..."
#echo "${slug}"

cd "${HOME}/notes/BlogPosts/eduk8me"

if [ ! -f "${post}" ]
then
# Put header on top
cat > "${post}"<< EOF
Title: "Edcerpts for ${pd}"
Date: "${dayofpost} 12:30:00"

## Internet Travels

_Edcerpts are my weekly round up of interesting links and ideas I discovered on the internet. It is published on Mondays for the previous week_

### Apps


### Pedagogy


### Technology


### Tips


### Pop Culture


### Pot Pourri


![Ryan Signature](https://eduk8.me/wp-content/uploads/2020/06/SignatureRyan.png)

Be sure to subscribe to my [YouTube channel](https://go.eduk8.me/youtube) and join your fellow educators on the [Eduk8me email list](https://eduk8.me/welcome)!
--

EOF
fi

echo "* [${title}](${surl})" >> ${post}
