#!/bin/bash

ACTION="Open Push"
TITLE="Push notification from `hostname`"
SUBTITLE="`date`"
ICONURL="https://dl.dropboxusercontent.com/u/172539/icons/vps.png"
SOUND=""

if [ -e ~/.goznotify ]; then
    source ~/.goznotify
else
    echo "Config file ~/.goznotify not found."
    exit
fi    

OPTIND=1
while getopts "a:t:u:s:i:b:" OPTION
do
	case $OPTION in
        a)
            ACTION=$OPTARG
            ;;
        t)
            TITLE=$OPTARG
            ;;
        u)
            URL=$OPTARG
            ;;
        s)
            SUBTITLE=$OPTARG
            ;;
        i)
            ICONURL=$OPTARG
            ;;
        b)
            SOUND=$OPTARG
            ;;
    esac
done
shift $((OPTIND-1))

MESSAGE=${1}
POSTDATE="{\"type\": \"note\", \"title\": \"${TITLE}\", \"body\": \"${MESSAGE}\"}"

# Send a notification
# curl --header 'Authorization: Bearer <your_access_token_here>' -X POST https://api.pushbullet.com/v2/pushes --header 'Content-Type: application/json' --data-binary '{"type": "note", "title": "Note Title", "body": "Note Body"}'
#if [ -z "${URL}" ]
#then
#    curl -s -X POST https://api.pushbullet.com/v2/pushes \
#        --header "Authorization: Bearer ${APIKEY}" \
#        --header 'Content-Type: application/json' \
#        --data-binary "{\"type\": \"note\", \"title\": \"${MESSAGE}\", \"body\": \"${TITLE} ${MESSAGE}\"}" > /dev/null
#else
#     curl -s -X POST https://api.pushbullet.com/v2/pushes \
#        --header "Authorization: Bearer ${APIKEY}" \
#        --header 'Content-Type: application/json' \
#        --data-binary "{\"type\": \"note\", \"title\": \"${MESSAGE}\", \"body\": \"${TITLE} ${MESSAGE}\"}" > /dev/null
#fi

#    /usr/bin/curl -s -d user_credentials=${APIKEY} \
#        -d "notification[long_message]=${MESSAGE}" \
#        -d "notification[title]=${TITLE}" \
#        -d "notification[sound]=${SOUND}" \
#        ${URL} > /dev/null

# Telegram Zuul

 /usr/bin/curl -s -X POST \
    https://api.telegram.org/bot${APIKEY}/sendMessage \
    -d text="${MESSAGE}" \
    -d chat_id=${TO} > /dev/null

# curl -s \
#     --form-string "token=${APIKEY}" \
#     --form-string "user=${USERKEY}" \
#     --form-string "message=${MESSAGE}" \
#     --form-string "title=${TITLE}" \
#     https://api.pushover.net/1/messages.json > /dev/null


#Faast

#    /usr/bin/curl -s -d user_credentials=${APIKEY} \
#       -d "notification[message]=${MESSAGE}" \
#       -d "notification[long_message]=${MESSAGE}" \
#       -d "notification[title]=${TITLE}" \
#       -d "notification[subtitle]=${SUBTITLE}" \
#        -d "notification[long_message_preview]=${MESSAGE}" \
#        -d "notification[message_level]=2" \
#        -d "notification[silent]=0" \
#        -d "notification[icon_url]=${ICONURL}" \
#        -d "notification[action_loc_key]=${ACTION}" \
#        -d "notification[run_command]=${URL}" \
#        https://api.faast.io/notifications.json > /dev/null
#
