#!/bin/bash

CURL="/usr/bin/curl"

if [ -e ~/.config/goznotify.conf ]; then
    source ~/.config/goznotify.conf
else
    echo "Config file ~/.config/goznotify.conf not found."
	echo "The config file needs the following:
APIKEY=\"\"        	#Telegram bot token
TO=\"\"				# Your chat id 
BOTGROUP=\"\"		# group id with topics
REDALERT=\"\"		# Critical alert thread id
YELLOWALERT=\"\"	# Warning thread id
"
    exit

fi    

sendTopic() {
# Telegram Zuul
	#echo "Posting to ${BOTGROUP} - ${TOPIC}"
	${CURL} -s -X POST \
    https://api.telegram.org/bot${APIKEY}/sendMessage \
    --data-urlencode text="${prefix}${MESSAGE}" \
	-d disable_web_page_preview=true \
    -d parse_mode="Markdown" \
	-d message_thread_id="${TOPIC}" \
    -d chat_id=${BOTGROUP} > /dev/null

}

level="$1"

# If first arg is a known level, shift it off. Otherwise treat everything as the message.
case "$level" in
alert|warn|info)
  shift
  ;;
*)
  level="info"
  ;;
esac

MESSAGE="$*"

case "$level" in
alert)
  thread="${REDALERT}"
  prefix="🚨 "
  ;;
warn)
  thread="${YELLOWALERT}"
  prefix="⚠️ "
  ;;
info)
  thread=""
  prefix=""
  ;;
esac

# Optional: export TOPIC for other parts of your script to inspect
TOPIC="$thread"

sendTopic
