#!/bin/bash

# Download a song from Youtube and send it to me over Telegram
# Requires youtube-dl and 
# [telegram-notify](https://github.com/NicolasBernaerts/debian-scripts/tree/master/telegram)

# Update youtube-dl
sudo youtube-dl -U

yturl="${1}"

#songname=$(/usr/local/bin/youtube-dl -o "%(title)s.%(ext)s" --get-filename "${yturl}")
songname=$(youtube-dl -o "%(title)s.%(ext)s" --get-filename "${yturl}")
#/usr/local/bin/youtube-dl -x -o "%(title)s.%(ext)s" --audio-format mp3 "${yturl}"
youtube-dl -x -o "%(title)s.%(ext)s" --audio-format mp3 "${yturl}"

${HOME}/.config/dotfiles/scripts/telegram-notify --user "-1001471206245" --text "${songname%.*}" --document "${songname%.*}.mp3"
