# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
        PATH="$HOME/.local/bin:$PATH"
fi

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# save history for multiple terminals

if [ ! -d "${HOME}/.bash_history_log" ]; then
    mkdir "${HOME}/.bash_history_log"
fi

HISTSUFFIX=`tty | sed 's/\///g;s/^dev//g'`
HISTFILE="$HOME/.bash_history_log/bash_history_$HISTSUFFIX"
HISTTIMEFORMAT="%y-%m-%d %H:%M:%S "

PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007";history -a'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

# Import local aliases
if [ -f ~/.bash_aliases.local ]; then
    source ~/.bash_aliases.local
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Adds the current branch to the bash prompt when the working directory is
# part of a Git repository. Includes color-coding and indicators to quickly
# indicate the status of working directory.
#
# To use: Copy into ~/.bashrc and tweak if desired.
#
# Based upon the following gists:
# <https://gist.github.com/henrik/31631>
# <https://gist.github.com/srguiwiz/de87bf6355717f0eede5>
# Modified by me, using ideas from comments on those gists.
#
# License: MIT, unless the authors of those two gists object :)

git_branch() {
    # -- Finds and outputs the current branch name by parsing the list of
    #    all branches
    # -- Current branch is identified by an asterisk at the beginning
    # -- If not in a Git repository, error message goes to /dev/null and
    #    no output is produced
    git branch --no-color 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

git_status() {
    # Outputs a series of indicators based on the status of the
    # working directory:
    # + changes are staged and ready to commit
    # ! unstaged changes are present
    # ? untracked files are present
    # S changes have been stashed
    # P local commits need to be pushed to the remote
    local status="$(git status --porcelain 2>/dev/null)"
    local output=''
    [[ -n $(egrep '^[MADRC]' <<<"$status") ]] && output="$output+"
    [[ -n $(egrep '^.[MD]' <<<"$status") ]] && output="$output!"
    [[ -n $(egrep '^\?\?' <<<"$status") ]] && output="$output?"
    [[ -n $(git stash list) ]] && output="${output}S"
    [[ -n $(git log --branches --not --remotes) ]] && output="${output}P"
    [[ -n $output ]] && output="|$output"  # separate from branch name
    echo $output
}

git_color() {
    # Receives output of git_status as argument; produces appropriate color
    # code based on status of working directory:
    # - White if everything is clean
    # - Green if all changes are staged
    # - Red if there are uncommitted changes with nothing staged
    # - Yellow if there are both staged and unstaged changes
    # - Blue if there are unpushed commits
    local staged=$([[ $1 =~ \+ ]] && echo yes)
    local dirty=$([[ $1 =~ [!\?] ]] && echo yes)
    local needs_push=$([[ $1 =~ P ]] && echo yes)
    if [[ -n $staged ]] && [[ -n $dirty ]]; then
        echo -e '\033[1;33m'  # bold yellow
    elif [[ -n $staged ]]; then
        echo -e '\033[1;32m'  # bold green
    elif [[ -n $dirty ]]; then
        echo -e '\033[1;31m'  # bold red
    elif [[ -n $needs_push ]]; then
        echo -e '\033[1;34m' # bold blue
    else
        echo -e '\033[1;37m'  # bold white
    fi
}

git_prompt() {
    # First, get the branch name...
    local branch=$(git_branch)
    # Empty output? Then we're not in a Git repository, so bypass the rest
    # of the function, producing no output
    if [[ -n $branch ]]; then
        local state=$(git_status)
        local color=$(git_color $state)
        # Now output the actual code to insert the branch and status
        echo -e "\x01$color\x02[$branch$state]\x01\033[00m\x02"  # last bit resets color
    fi
}

# Sample prompt declaration. Tweak as you see fit, or just stick
# "$(git_prompt)" into your favorite prompt.
PS1='\u@\h:\w$(git_prompt)\[\033[00m\]\$ '


PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $(git_prompt)\$ ' 

# wp-cli functions
getdrafts() {
    MONTH=$1
    if [[ -z ${MONTH} ]]; then MONTH=$(date +"%m"); fi

    YEAR=$2
    if [[ -z ${YEAR} ]]; then YEAR=$(date +"%Y"); fi

    wp @e post list --year=${YEAR} --monthnum=${MONTH} --post_status=draft --order=asc
}

getpending() {
    MONTH=$1
    if [[ -z ${MONTH} ]]; then MONTH=$(date +"%m"); fi
    wp @e post list --year=$(date +"%Y") --monthnum=${MONTH} --post_status=pending --order=asc
}

editpost() {
    wp @e post edit $1
}

setpending() {
    POST=$1
    if [[ ! -z ${POST} ]]; then
        wp @e post update ${POST} --post_status=pending
    else
        echo "No post id"
    fi
}

post() {
    MSG=$1
    wp @r post create --format=status --post_content="${MSG}" --post_title="${MSG}" --post_category=355
}

,je() {
    ENTRY=$1
    echo -e "\n`date  +\"%Y/%m/%d %R\"` - ${1}" >> ~/notes/Journal/`date +"%Y"`.md
}

,uz() {
    file="${1%.zip}"

    mkdir ${file}
    cd ${file}
    unzip ../${1}
    
}

,findnote() {
    searchfor=$(echo "${*}" | sed 's/[]\/$*.^|#[]/\\&/g')
    echo "Searching all notes for ${searchfor}..."
    grep -riH --include "*.md" "${searchfor}" "${HOME}/notes"
}

# set PATH so it includes the scripts folder  if it exists
if [ -d "$HOME/.config/dotfiles/scripts" ] ; then
        PATH="$HOME/.config/dotfiles/scripts:$PATH"
fi

# Bashmarks
#unalias l
source bashmarks.sh

# Fix ls
export QUOTING_STYLE=literal

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


if [ -f ${HOME}/.local/bin/zoxide ]; then
    eval "$(zoxide init --cmd cd bash)"
fi

# Launch Yazi
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

function today() {
	local TODAY=$(date +"%m/%d/%Y")
	r search -l Daily --due-before ${TODAY} --uncompleted
}

pyproject() {
    local base_dir="$HOME/Development"
    local project_name="$1"
    local project_dir
    local venv_path
    local selection

    mkdir -p "$base_dir" || return 1

    if [[ -z "$project_name" ]]; then
        selection=$(
            {
                find "$base_dir" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;
                echo "[Create new project]"
            } | sort | fzf --prompt="Project> " --height=40% --reverse
        ) || return 1

        if [[ "$selection" == "[Create new project]" ]]; then
            read -r -p "New project name: " project_name
            [[ -n "$project_name" ]] || return 1
        else
            project_name="$selection"
        fi
    fi

    project_dir="$base_dir/$project_name"

    mkdir -p "$project_dir" || return 1
    cd "$project_dir" || return 1

    if command -v git >/dev/null 2>&1 && [[ ! -d .git ]]; then
        git init || return 1
    fi

    if [[ -d .git ]]; then
        [[ -f .gitignore ]] || touch .gitignore
        grep -qxF '.venv' .gitignore || echo '.venv' >> .gitignore
    fi

    [[ -d .venv ]] || python3 -m venv .venv || return 1

    venv_path="$PWD/.venv"
    [[ "$VIRTUAL_ENV" == "$venv_path" ]] || source .venv/bin/activate || return 1
}

_pyproject_completions() {
    local cur base_dir
    cur="${COMP_WORDS[COMP_CWORD]}"
    base_dir="$HOME/Development"

    COMPREPLY=()
    [[ -d "$base_dir" ]] || return 0

    COMPREPLY=( $(compgen -W "$(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -printf '%f\n')" -- "$cur") )
}

complete -F _pyproject_completions pyproject

# -----------------------------------------------------------------------------
# SSH / Mosh fuzzy host selector
#
# Usage:
#   sshs                         Open fzf host picker
#   sshs host                    SSH directly if host is an exact configured Host
#   sshs partial                 Open fzf with "partial" as the search
#   sshs user@host               SSH directly as user
#   sshs user@partial            Fuzzy-search hosts, preserving user@
#   sshs user@host<Tab>          Tab-complete hosts, preserving user@
#
# In fzf:
#   Enter                        Connect with SSH
#   Alt-M                        Connect with Mosh
#   Esc                          Cancel
#
# Hosts are collected recursively from:
#   ~/.ssh/config
#   /etc/ssh/ssh_config
#   Any files referenced by Include directives
#
# Duplicate hosts and wildcard Host patterns are ignored.
# -----------------------------------------------------------------------------


_sshs_hosts() {
    declare -A seen_files=()
    declare -A seen_hosts=()

    _sshs_parse_config() {
        local file="$1"
        local config_type="$2"
        local line keyword rest pattern included host
        local -a parts

        [[ -f "$file" && -r "$file" ]] || return

        # Avoid recursive Include loops
        [[ ${seen_files["$file"]+yes} ]] && return
        seen_files["$file"]=1

        while IFS= read -r line || [[ -n "$line" ]]; do

            # Strip comments
            line="${line%%#*}"

            # Trim leading whitespace
            line="${line#"${line%%[![:space:]]*}"}"

            # Trim trailing whitespace
            line="${line%"${line##*[![:space:]]}"}"

            [[ -z "$line" ]] && continue

            keyword="${line%%[[:space:]]*}"
            rest="${line#"$keyword"}"

            # Trim whitespace before arguments
            rest="${rest#"${rest%%[![:space:]]*}"}"

            case "${keyword,,}" in

                host)
                    read -ra parts <<< "$rest"

                    for host in "${parts[@]}"; do

                        # Ignore patterns such as:
                        #   Host *
                        #   Host *.example.com
                        #   Host !foo
                        [[ "$host" == *[\*\?\!]* ]] && continue

                        # Remove duplicates while preserving discovery order
                        if [[ ! ${seen_hosts["$host"]+yes} ]]; then
                            seen_hosts["$host"]=1
                            printf '%s\n' "$host"
                        fi
                    done
                    ;;

                include)
                    read -ra parts <<< "$rest"

                    for pattern in "${parts[@]}"; do

                        # Expand ~/...
                        if [[ "$pattern" == "~/"* ]]; then
                            pattern="$HOME/${pattern#~/}"

                        # Relative paths in the user's config are relative
                        # to ~/.ssh
                        elif [[ "$pattern" != /* &&
                                "$config_type" == "user" ]]; then
                            pattern="$HOME/.ssh/$pattern"

                        # Relative paths in the system config are relative
                        # to /etc/ssh
                        elif [[ "$pattern" != /* ]]; then
                            pattern="/etc/ssh/$pattern"
                        fi

                        # Expand Include globs in lexical order
                        while IFS= read -r included; do
                            [[ -n "$included" ]] || continue

                            _sshs_parse_config \
                                "$included" \
                                "$config_type"

                        done < <(
                            compgen -G "$pattern" | sort
                        )
                    done
                    ;;
            esac

        done < "$file"
    }

    # User SSH configuration
    _sshs_parse_config "$HOME/.ssh/config" "user"

    # System-wide SSH configuration
    _sshs_parse_config "/etc/ssh/ssh_config" "system"

    unset -f _sshs_parse_config
}


sshs() {
    local argument="${1:-}"
    local query="$argument"
    local username=""
    local destination
    local host key
    local -a result
    local hosts

    hosts="$(_sshs_hosts)"

    # Split user@host if a username was supplied.
    if [[ "$argument" == *@* ]]; then
        username="${argument%@*}"
        query="${argument##*@}"
    fi

    # If the host portion is an exact configured Host,
    # skip fzf and SSH directly.
    if [[ -n "$query" ]] &&
       grep -Fxq -- "$query" <<< "$hosts"; then

        if [[ -n "$username" ]]; then
            ssh "${username}@${query}"
        else
            ssh "$query"
        fi

        return
    fi

    # Otherwise launch fzf using only the hostname portion
    # as the search query.
    mapfile -t result < <(
        printf '%s\n' "$hosts" |
            fzf \
                --query="$query" \
                --prompt="Host> " \
                --header="Enter: SSH   Alt-M: Mosh   Esc: Cancel" \
                --expect=enter,alt-m
    )

    key="${result[0]:-}"
    host="${result[1]:-}"

    # Esc or otherwise cancelled
    [[ -n "$host" ]] || return

    # Reattach username, if supplied
    if [[ -n "$username" ]]; then
        destination="${username}@${host}"
    else
        destination="$host"
    fi

    case "$key" in
        alt-m)
            mosh "$destination"
            ;;

        enter|"")
            ssh "$destination"
            ;;
    esac
}


_sshs_completion() {
    local cur
    local username=""
    local hostpart
    local host
    local -a matches

    cur="${COMP_WORDS[COMP_CWORD]}"
    hostpart="$cur"

    # Preserve user@ while completing only the hostname.
    if [[ "$cur" == *@* ]]; then
        username="${cur%@*}@"
        hostpart="${cur##*@}"
    fi

    mapfile -t matches < <(
        compgen -W "$(_sshs_hosts)" -- "$hostpart"
    )

    COMPREPLY=()

    for host in "${matches[@]}"; do
        COMPREPLY+=("${username}${host}")
    done
}


# Enable tab completion for sshs
complete -F _sshs_completion sshs

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"

# [[ -n $SSH_TTY ]] && tma main

# Export working directory for terminals [Shell working directory reporting · Eugeny/tabby Wiki](https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting)
export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Import local bash settings
# include `PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"` if on a Mac with coreutils provided by brew
if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi

