source ~/.bashrc

export PATH=/home/goz/.go/bin:$PATH

export GOPATH=/home/goz/go

export PATH=/home/goz/go/bin:$PATH
if [ -e /home/goz/.nix-profile/etc/profile.d/nix.sh ]; then . /home/goz/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
. "/home/sysadmin/.deno/env"
source /home/sysadmin/.local/share/bash-completion/completions/deno.bash